// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0D3vFz6BEHts-LzpwfVwNhcqPFNfZMpY',
    appId: '1:383822184708:web:7a321f4e9805840e485051',
    messagingSenderId: '383822184708',
    projectId: 'fir-tutorial-b58db',
    authDomain: 'fir-tutorial-b58db.firebaseapp.com',
    storageBucket: 'fir-tutorial-b58db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7-7I_n79SpmelNlQBkhWpgpqpPI71fLo',
    appId: '1:383822184708:android:033c077e46d78d68485051',
    messagingSenderId: '383822184708',
    projectId: 'fir-tutorial-b58db',
    storageBucket: 'fir-tutorial-b58db.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0D3vFz6BEHts-LzpwfVwNhcqPFNfZMpY',
    appId: '1:383822184708:web:828b07e2f050706f485051',
    messagingSenderId: '383822184708',
    projectId: 'fir-tutorial-b58db',
    authDomain: 'fir-tutorial-b58db.firebaseapp.com',
    storageBucket: 'fir-tutorial-b58db.firebasestorage.app',
  );
}
